SLACK_CHANNEL_NAME: build-status
ENVIRONMENT: prod
CODE_BASE_PATH: Assignment-6
ACTION_MESSAGE: "Ansible deployment for Assignment6"
KEEP_APPROVAL_STAGE: true

ANSIBLE:
  PLAYBOOK: site.yml
  INVENTORY: inventory

GIT:
  URL: https://github.com/swapneel1026/ansible_mongodb_install.git
  BRANCH: master
